### ISSUE TITLE
  pixray.add_settings(drawer="pixel")

### ISSUE THREAD

**Issue by baldonazionale** [dribnet/pixray#7] opened 2021-09-23 19:59 UTC
`pixray.add_settings(drawer="pixel")`

this setting generates an error:

`KeyError: 'pixel'`

**Comment by rvorias** [comment] 2021-09-27 08:44
Your `class_table` might not have been updated.
```
try:
    from clipdrawer import ClipDrawer
    from pixeldrawer import PixelDrawer
    from linedrawer import LineDrawer
    # update class_table if these import OK
    class_table.update({
        "line_sketch": LineDrawer,
        "pixel": PixelDrawer,
        "clipdraw": ClipDrawer
    })
except ImportError:
    # diffvg is not strictly required
    pass
```

Can you verify if those import statements work?

**Comment by dribnet** [comment] 2021-09-27 10:30
Ah yes, I should probably make a more meaningful error message here. The issue is that I want the software to work in VQGAN mode if the gnarly diffvg dependency is not available. But this means that if the dependency fails you don't know about it until you request pixel mode. Perhaps better would be to import the dependency when requested (reporting errors) and not conditionally at the top of the file (ignoring errors).

**Comment by dribnet** [comment] 2021-10-03 11:20
going to close this out for now, but feel free to re-open if this happens again and we can track down where to stick in a better error message.

**Closed by dribnet** 2021-10-03 11:20 UTC
